Add tests to ci.yaml file (#6)
* Add tests to ci.yaml file

* test zoom in workflow

* fix bad parameters

* add volume, use local docker image

* only build amd64 so load works

* remove :latest

* lower zoom level for test

* Revert "lower zoom level for test"

This reverts commit d71ffc8dd9e788a0448f90969ee5c655e3cf8da4.

* use smaller test data file

* put back outputMaxZoom 6

---------

Co-authored-by: acalcutt <acalcutt@techidiots.net>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,7 @@ on:
   pull_request:
     branches:
       - main
+  workflow_dispatch:
 
 concurrency:
   group: ci-${{ github.ref }}-1
@@ -40,8 +41,28 @@ jobs:
         with:
           context: .
           push: false
-          tags: wifidb/contour-generator:latest, wifidb/contour-generator:v${{ steps.version.outputs.version }}
-          platforms: linux/arm64,linux/amd64
-          # experimental: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
+          load: true
+          tags: contour-generator
+          platforms: linux/amd64
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+      - name: End to End Test pyramid
+        run: |
+          docker run --rm contour-generator pyramid --z 9 --x 272 --y 179 --demUrl "pmtiles://https://acalcutt.github.io/contour_generator/test_data/terrain-tiles.pmtiles" --sourceMaxZoom 12  --encoding mapbox  --increment 0  --outputDir "./output_pyramid"  --outputMaxZoom 15  -v
+
+      - name: End to End Test bbox
+        run: |
+          docker run --rm contour-generator bbox --minx -73.51 --miny 41.23 --maxx -69.93 --maxy 42.88 --demUrl "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png" --sourceMaxZoom 15 --encoding terrarium --increment 50 --outputMinZoom 5 --outputMaxZoom 10 --outputDir "./output_bbox" -v
+
+      - name: Download Test Data
+        run: |
+          curl -L -o JAXA_2024_terrainrgb_z0-Z6_webp.pmtiles https://github.com/acalcutt/contour_generator/releases/download/test_data/JAXA_2024_terrainrgb_z0-Z6_webp.pmtiles
+          if [[ $? -ne 0 ]]; then
+             echo "Error downloading the test data!"
+             exit 1
+          fi
+
+      - name: End to End Test zoom
+        run: |
+          docker run --rm -v $(pwd):/data contour-generator zoom --demUrl "pmtiles:///data/JAXA_2024_terrainrgb_z0-Z6_webp.pmtiles" --sourceMaxZoom 6 --encoding mapbox --outputMinZoom 5 --outputMaxZoom 6 --increment 100 --processes 4 --outputDir "./output_zoom" -v
